"""users table

Revision ID: f012e54c08b5
Revises: 
Create Date: 2023-07-18 12:11:48.148645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f012e54c08b5'
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
                    sa.Column('password', sa.VARCHAR(
                        length=150), nullable=True),
                    sa.Column('first_name', sa.VARCHAR(
                        length=50), nullable=True),
                    sa.Column('last_name', sa.VARCHAR(
                        length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###
